apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: devops
  # annotations:
  #   eks.amazonaws.com/role-arn: "<%= ENV['TEKTON_SA_ROLE_ARN'] %>"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-role
rules:
- apiGroups: ["*"]
  resources: ["namespaces", "configmaps", "secrets", "deployments", "serviceaccounts", "roles", "rolebindings", "statefulsets", "services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-role
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: devops
