apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: devops
  # annotations:
  #   eks.amazonaws.com/role-arn: "<%= ENV['TEKTON_SA_ROLE_ARN'] %>"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-role
  namespace: devops
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-role-binding
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-role
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: devops
