apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tekton-pipelines
  name: config-defaults
data:
  default-timeout-minutes: "60"
  # default-pod-template: |
  #   nodeSelector:
  #     eks.amazonaws.com/nodegroup: code
  default-managed-by-label-value: "tekton-pipelines"
  default-task-run-workspace-binding: |
    emptyDir: {}
